builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
      - openbsd
      - solaris
      ## windows support is still iffy
      #- windows
    main: ./cmd/terrajux
    ldflags: -s -w -X github.com/rhenning/terrajux.Version={{.Version}}
archives:
  - wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    ## may enable these, but leaving disabled atm to align w/ terraform
    # - replacements:
    #     darwin: Darwin
    #     linux: Linux
    #     windows: Windows
    #     386: i386
    #     amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{.Tag}}-snapshot+{{.Timestamp}}.{{.ShortCommit}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
